### ISSUE TITLE
[Bug]: Can't use rules_rollup: @@aspect_bazel_lib//lib:coreutils_toolchain_type was requested byt only types [] are configured

### ISSUE THREAD

**Issue by peak-taekwondo** [aspect-build/rules_rollup#89]
### What happened?

I'm trying to use rollup from Aspect in my build (I can't use esbuild because I'm doing lit-element development using decorators and that isn't supported by esbuild), but I get an error when I bazel build it saying:

```
Error: In _rollup rule //typescript/lit:bundle, toolchain type @@aspect_bazel_lib//lib:coreutils_toolchain_type was requested but only types [] are configured
```

### Version

Development (host) and target OS/architectures: Ubuntu linux 22.04.2 LTS/11th Gen Intel® Core™ i7-1195G7 @ 2.90GHz × 8

Output of `bazel --version`: bazel 7.0.0

Version of the Aspect rules, or other relevant rules from your
`WORKSPACE` or `MODULE.bazel` file:
    bazel_lib: 2.2.0
    rules_js: 1.35.0
    rules_ts: 2.1.0
    rules_rollup: 1.0.0

Language(s) and/or frameworks involved:
    TypeScript, LitElement

**Comment by peak-taekwondo** [comment]
Any guidance here would be greatly appreciated. I can't seem to use webpack either, and as I stated in my original bug, esbuild is insufficient due to its inability to handle decorators which are a key part of making LitElement work in a reasonable way.

**Comment by archen** [comment]
my PRs are above, if you want to work around the issue pre-approval you're welcome to try from my commit

```
git_override(
    module_name = "aspect_rules_rollup",
    remote = "https://github.com/archen/rules_rollup",
    commit = "d8d982c1894c0a994203a71a357b4e710bdd94d4",
)
```

**Comment by bejaneps** [comment]
Facing same issue, could someone merge above pr please ?

I'm going to use @archen 's override

**Comment by alexeagle** [comment]
@bejaneps thanks for the ping, it's merged now. I'll cut a release.

**Comment by pward123** [comment]
@alexeagle Running into this issue still. Can we cut a release?

**Comment by pward123** [comment]
ack, never mind. I saw latest release was 1.0.0 on the main github page, but going into releases shows the 1.0.1
